---
title: "Building an R package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rpkg_build}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## R package workshop guide
@[GLBIO 2023](//github.com/jravilab/2023-glbio)

### Create the package directory
1. Set pkg path: `pkg_path <- file.path("PATH/TO/RPKG_DIR")`
2. `dir.create(pkg_path)`
3. `setwd(pkg_path)`

### Install packages needed for this package's development
`pkgs <- c("devtools", "BiocManager", "Biostrings", "httr", "tidyverse)`
`install.packages(pkgs)`

## Create package

- `library(devtools, usethis)`
- `usethis::create_package(pkg_path)` 
- reload libraries
- `usethis::use_git()`
- reload libraries
- `use_r("submit_ipr.R")`
- Write functions (or copy and paste)

### Paste this into the ipr_submit.R file:

```
.split_seqs <- function(fasta_path, outfolder) {

  cat("Splitting sequences\n", sep = "")

  tmp <- file.path(outfolder, "tmp")
  if (!(dir.exists(tmp))) {
    dir.create(tmp)
  }

  n_seqs <- nrow(Biostrings::fasta.index(fasta_path))
  i <- 0L
  while (n_seqs > 0) {
    #n_read <- ifelse(n_seqs < 30, n_seqs, 30L)
    single_seq <- Biostrings::readAAStringSet(fasta_path, nrec = 1L, skip = i)
    seq_header <- names(single_seq)[[1]]
    # try to fix filenames
    if (grepl(" ", seq_header)) {
      seq_filename <- unlist(strsplit(seq_header, " "))[[1]]
    }
    else {
      seq_filename <- stringr::str_replace_all(seq_header, "[^[:alnum:]]", "")
    }
    out <- file.path(tmp, seq_filename)
    Biostrings::writeXStringSet(single_seq, out)

    # subtract seqs and add skipping index for next read
    n_seqs <- n_seqs - 1L
    i <- i + 1L
  }
  # return the tmp outfolder path
  print('Exiting .split_seqs()')
  return(tmp)
}

.submit <- function(path2seq, outfile, user_email) {

  ### POST
  url_post <- 'https://www.ebi.ac.uk/Tools/services/rest/iprscan5/run'
  fasta <- Biostrings::readAAStringSet(path2seq)
  fasta_header <- names(fasta)[[1]]
  sequence_str <- as.character(fasta[[1]])
  print(fasta)
  headers_post <- c("Accept: text/plain", "Content-Type: application/x-www-form-urlencoded")

  # job params
  data <- list(
    email=user_email,
    title="test",
    goterms="false",
    pathways="false",
    stype="p",
    appl="PfamA",
    sequence=sequence_str
  )

  res_post <- httr::POST(url_post, body = data, httr::add_headers(headers_post))
  cat("Request: \n", sep = "")
  print(res_post$request)
  if (as.integer(res_post$status) != 200L) {
    message <- paste0("POST error with sequence: ", fasta_header, "\n",
                      "Status code: ", as.integer(res_post$status), "\n")
    warning(message)
    return(NULL)
  }
  else {
    cat("POST status: ", as.integer(res_post$status), "\n", sep = "")
  }
  job_id <- rawToChar(res_post$content)
  cat("job_id: ", job_id, "\n", sep = "")

  ### GET
  url_get_base <- "https://www.ebi.ac.uk/Tools/services/rest/iprscan5/result/"
  url_get <- paste0(url_get_base, job_id, "/tsv")
  header_get <- "Accept: text/tab-separated-values"

  status <- -1L
  n_polls <- 1L
  # Try poll 30 times OR until status is complete
  while (status != 200L && n_polls < 30L) {
    res_get <- httr::GET(url_get, httr::add_headers(header_get))
    status <- as.integer(res_get$status_code)
    cat("GET poll #", n_polls, "\t", "Status: ", status, "\n", sep = "")
    n_polls <- n_polls + 1L
    Sys.sleep(30L)
  }
  if (status != 200L) {
    message <- paste0("Failed to retrieve job results for <",
                      job_id,
                      ">",
                      "\n",
                      "Job exceeded 30 minutes runtime.")
    warning(message)
    return(NULL)
  }
  # parse and write tsv
  print(rawToChar(res_get$content))
  writeBin(res_get$content, paste0(outfile, ".tsv"))
  cat(job_id, " complete\n", "Output file located at ", outfile, "\n", sep = "")

  return(TRUE)
}

submit_ipr <- function(path2seq, outfolder, email) {
#' @export
#' @title Submit IPRscan analysis for protein sequences (multifasta input)
#' @param path2seq path to your sequence file
#' @param outfolder location for IPRscan outputs
#' @param email required email ID for job submission (to track and prevent accidental misuse of the API)
#' @keywords domains, domain architectures, protein characterization

  outfolder <- file.path(outfolder)
  if (!(dir.exists(outfolder))) {
    dir.create(outfolder)
  }

  # test if input is a multifasta file
  n_seqs <- nrow(Biostrings::fasta.index(path2seq))

  if (n_seqs == 1L) {
    cat("Single sequence detected", "\n", sep = "")
    outfile <- file.path(outfolder, "iprout")
    .submit(path2seq, outfile, email)
    cat("Full submission complete. Results located at: ",
        outfolder, "\n", sep = "")
    return(outfolder)
  }

  cat("Multiple sequences detected", "\n", sep = "")
  split_seqs_folder <- .split_seqs(path2seq, outfolder)

  seq_i <- 1L
  seq_n <- length(list.files(split_seqs_folder))
  n_successes <- 0L
  for (seq_cur in list.files(split_seqs_folder)) {
    seq_cur_path <- file.path(split_seqs_folder, seq_cur)
    outfile <- file.path(outfolder, strsplit(seq_cur, ".faa"[[1]]))
    success <- as.integer(.submit(seq_cur_path, outfile, email))
    cat("Seq # ", seq_i, "/", seq_n, " completed\n", sep = "")
    seq_i <- seq_i + 1L
  }

  cat("Full submission complete. Results located at: ",
      outfolder, "\n", sep = "")
  return(outfolder)
}
```

- **Access the local package's functions**: `load_all()`

***

### Test
- Create a folder to house sample data: `dir.create(file.path(pkg_path, "inst", "extdata"), recursive = TRUE)`

- Create a file called "input.faa" and paste the following content inside
```
>CAA75348.1 voltage gated potassium channel [Homo sapiens]
MVQKSRNGGVYPGPSGEKKLKVGFVGLDPGAPDSTRDGALLIAGSEAPKRGSILSKPRAGGAGAGKPPKR
NAFYRKLQNFLYNVLERPRGWAFIYHAYVFLLVFSCLVLSVFSTIKEYEKSSEGALYILEIVTIVVFGVE
YFVRIWAAGCCCRYRGWRGRLKFARKPFCVIDIMVLIASIAVLAAGSQGNVFATSALRSLRFLQILRMIR
MDRRGGTWKLLGSVVYAHSKELVTAWYIGFLCLILASFLVYLAEKGENDHFDTYADALWWGLITLTTIGY
GDKYPQTWNGRLLAATFTLIGVSFFALPAGILGSGFALKVQEQHRQKHFEKRRNPAAGLIQSAWRFYATN
LSRTDLHSTWQYYERTVTVPMYRLIPPLNQLELLRNLKSKSGLAFRKDPPPEPSPSQKVSLKDRVFSSPR
GVAAKGKGSPQAQTVRRSPSADQSLEDSPSKVPKSWSFGDRSRARQAFRIKGAASRQNSEEASLPGEDIV
DDKSCPCEFVTEDLTPGLKVSIRAVCVMRFLVSKRKFKESLRPYDVMDVIEQYSAGHLDMLSRIKSLQSR
VDQIVGRGPAITDKDRTKGPAEAELPEDPSMMGRLGKVEKQVLSMEKKLDFLVNIYMQRMGIPPTETEAY
FGAKEPEPAPPYHSPEDSREHVDRHGCIVKIVRSSSSTGQKNFSAPPAAPPVQCPPSTSWQPQSHPRQGH
GTSPVGDHGSLVRIPPPPAHERSLSAYGGGNRASMEFLRQEDTPGCRPPEGTLRDSDTSISIPSVDHEEL
ERSFSGFSISQSKENLDALNSCYAAVAPCAKVRPYIAEGESDTDSDLCTPCGPPPRSATGEGPFGDVGWA
GPRK

```
- Submit job using the library's function:
`ipr_submit(file.path("./inst/extdata/input.faa"), "single-out")`

- Check output: `readLines("./single-out/iprout.tsv")`

**Note**: You can reference files within a package directory, such as data files, by using:  `system.file("PATH/FROM/PKG/ROOT/", package = "PKGNAME)` 

This is useful for scripts that need to access data from their package. If a user loads the library on their computer, this provides a way to find the proper path to the package's data contents.

For example,

`readLines(system.file("single-out/iprout.tsv", package = "testPkg"))`

## Final checks

- Check if the package can build properly: `devtools::check()`
- Fix any errors/warnings
- Create a license: `usethis::use_mit_license()`
- Specify imports/depends: `usethis::use_package()`
- `usethis::use_package('httr')`
- `usethis::use_package('Biostrings')`
- `usethis::use_package('stringr')`
- Edit DESCRIPTION file
  - Title
  - Author
  - Description
- To document, place cursor inside a function definition block: `Code > Insert Roxygen Skeleton`
  - Fill out fields
- `document()`
  - Creates a .Rd file in the man/ folder
  - Updates namespace with exported functions
- Recheck: `devtools::check()`
- Install and test: 
  - `install()`
  - `library(testPkg)`
  - View help: `?testPkg::ipr_submit`
  - `testPkg::ipr_submit(...)`

## Next steps
- Pushing to GitHub
- `use_testthat()` for streamlined testing
- Publishing to GitHub, BioConductor, or CRAN.
